### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [yakirwin/lev-isha#2]
- לא פתחתם issue
- דף צוות לא מפורט מספיק על שונות הצוות
- חסר עוד פרטים וקישורים בreadme, כמו הפניה למדריך למשתמש וכל מה שיש בויקי
- יש דברים חופפים בסיכונים

**Comment by yakirwin** [comment]
יש issue שקוראים לו SRS 
אתה לא רואה אותו? 
שמתי אותך שם :/

**Comment by yakirwin** [comment]
@kob-e

**Comment by tchvu3** [comment]
- ישנו issue פתוח (כבר היה פתוח מקודם)
- שונות הצוות עודכנה
- כל הלינקים סודרו ונוספו כל הלינקים החסרים ברידמי
- נמחקו הסיכונים החופפים ונוספו סיכונים נוספים

**Comment by JonathanMai** [comment]
מה צריך לשנות\להוסיף?

**Comment by YaakovHatam** [comment]
@tchvu3 @JonathanMai  @yakirwin  אם לא שמתם לב זהו פידבק על המשימה inception 
כתוב בהוראות הגשה שצריך לפתוח issue

> פתיחת משימה (issue) במאגר הקורס בשם: Check Project 2 Submission ושיוכה למתרגל (הסבר בהמשך - כך תתבצע גם ההגשה במשימות הפרויקט הבאות)

תפתחו issue לפי ההוראות ותייגו אותי בפנים

**Comment by YaakovHatam** [comment]
עדכנתי לכם, עבודה יפה.

**Comment by yakirwin** [comment]
עדכנו את הרידמי - הוספנו כותרת משנה, שינינו והוספנו לינקים כמו לינקים בכלים ושיטות, פרוטוטייפ ודפי איטרציות
דף הרידמי של אינספשטיון - הסיכונים שופרו, הקישורים שופרו
דף צוות - שונות עודכנה ושופרה, עכשיו יותר עניינית
