### ISSUE TITLE
#3 - SRS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [yakirwin/lev-isha#3]
## TODO:
- Please attach here the Client review.

## סיכום פגישתנו:
יש אתר קיים שצריך להמיר לאפליקציה, לא מובן למה אפשר לעטוף את האתר אין פרויקט הנדסי אין סיכונים

**Comment by yakirwin** [comment]
קישרנו לסיכונים ולפרוטוטייפ בתחילת הSRS
@kob-e

**Comment by yakirwin** [comment]
מבוא - עכשיו יש גם מבוא לפרויקט ולדף 
סקירת לקוח - עודכנה סקירת הלקוח והוספה הבקשה בשיחה האחרונה לאחר עוד שיחה
פרוטוטייפ - עדכון הקישור
סיכונים - עכשיו הסיכונים מופיעים ישר ועם העדכונים וההרחבות
