### ISSUE TITLE
Check Project 2 Submission

### ISSUE THREAD

**Issue by JonathanMai** [yakirwin/lev-isha#4]
Check Project 2 Submission issue.

@kob-e

**Comment by JonathanMai** [comment]
@kob-e  האם התכוונת ללפתוח פשוט issue בצורה הזאת?
כתוב בתרגיל לפתוח אך אין הנחיות לאיך לפתוח, אם צריך פשט לפתוח ולקשר אותך ככה שתדע שעשינו את התרגיל או שצריך להוסיף לינקים רלוונטים

**Comment by YaakovHatam** [comment]
@JonathanMai ככה בדיוק

**Comment by YaakovHatam** [comment]
Feedback at #2
